version: "3"
services:
    app:
        restart: always
        build: .
        command: "python3 manage.py runserver 0.0.0.0:8000"
        volumes:
            - .:/sc_backend
        ports:
            - "8000:8000"