# Generated by Django 3.2.4 on 2021-07-09 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0003_rename_comment_comment_opinion'),
        ('graph', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonComment',
            fields=[
                ('id', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('account1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='common_user1', to='data_api.user')),
                ('account2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='common_user2', to='data_api.user')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_pair', to='data_api.article')),
            ],
        ),
    ]
