# Generated by Django 3.2.4 on 2021-07-09 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0002_commoncomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='commoncomment',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
