# Generated by Django 3.2.4 on 2021-07-10 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0003_commoncomment_weight'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommonComment',
        ),
    ]
