# Generated by Django 3.2.4 on 2021-07-10 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0004_delete_commoncomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='value',
            field=models.FloatField(),
        ),
    ]
