# Generated by Django 3.2.4 on 2021-06-22 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('board', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('ip', models.CharField(max_length=15)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=12, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction', models.CharField(max_length=1)),
                ('comment', models.TextField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('ip', models.CharField(max_length=15)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussions', to='data_api.article')),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='data_api.user')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='original_poster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='data_api.user'),
        ),
    ]
