# Generated by Django 3.2.4 on 2021-07-08 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0002_auto_20210708_2145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='opinion',
        ),
    ]
