# Generated by Django 3.2.4 on 2021-07-10 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0004_commoncomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commoncomment',
            name='article',
        ),
    ]
